"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
var jsx_runtime_1 = require("react/jsx-runtime");
var react_router_dom_1 = require("react-router-dom");
var Layout_1 = require("../layout/Layout");
var Main_1 = require("@pages/Main/Main");
var InHelper_1 = require("@pages/InHelper/InHelper");
var CompareText_1 = require("@pages/CompareText/CompareText");
var GraylogConverter_1 = require("@pages/GraylogConverter/GraylogConverter");
exports.router = (0, react_router_dom_1.createBrowserRouter)((0, react_router_dom_1.createRoutesFromElements)((0, jsx_runtime_1.jsxs)(react_router_dom_1.Route, { path: '/', element: (0, jsx_runtime_1.jsx)(Layout_1.Layout, {}), children: [(0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: '/', element: (0, jsx_runtime_1.jsx)(Main_1.Main, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: '/in-helper', element: (0, jsx_runtime_1.jsx)(InHelper_1.InHelper, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: '/compare-text', element: (0, jsx_runtime_1.jsx)(CompareText_1.CompareText, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/graylog-converter", element: (0, jsx_runtime_1.jsx)(GraylogConverter_1.GraylogConverter, {}) })] })));
